export const homepageSectionOrder = [
  "hero",
  "introduction",
  "statistics",
  "mission-vision",
  "values",
  "history",
  "activities",
  "members",
  "diaspora",
  "community",
  "interviews",
  "awards",
  "events",
  "gallery",
  "news",
  "join",
  "contact",
] as const;
