export const positions = [
  ["GK", "Gardien", 6, 3],
  ["SW", "Libéro", 5, 3],
  ["LB", "Arrière gauche", 4, 1],
  ["LWB", "Piston gauche", 3, 1],
  ["LCB", "Défenseur central gauche", 4, 2],
  ["CB", "Défenseur central", 4, 3],
  ["RCB", "Défenseur central droit", 4, 4],
  ["RB", "Arrière droit", 4, 5],
  ["RWB", "Piston droit", 3, 5],
  ["LM", "Milieu gauche", 2, 1],
  ["LCM", "Milieu central gauche", 2, 2],
  ["CDM", "Milieu défensif", 3, 3],
  ["CM", "Milieu central", 2, 3],
  ["RCM", "Milieu central droit", 2, 4],
  ["RM", "Milieu droit", 2, 5],
  ["CAM", "Milieu offensif", 1, 3],
  ["LW", "Ailier gauche", 0, 1],
  ["RW", "Ailier droit", 0, 5],
  ["SS", "Second attaquant", 1, 2],
  ["CF", "Avant-centre", 1, 4],
  ["ST", "Attaquant de pointe", 0, 3],
] as const;
export const positionOptions = positions.map(
  ([code, label]) => [code, `${code} — ${label}`] as const,
);
export const legacyPositions: Record<string, string> = {
  goalkeeper: "GK",
  right_back: "RB",
  left_back: "LB",
  centre_back: "CB",
  defensive_midfielder: "CDM",
  central_midfielder: "CM",
  attacking_midfielder: "CAM",
  right_winger: "RW",
  left_winger: "LW",
  second_striker: "SS",
  striker: "ST",
};
